csparse.c File Reference
#include <stdlib.h>
*
#include <limits.h>
*
#include <math.h>
*
#include <stdio.h>
*
#include `csparse.h`
*
Functions
cs * cs_add (const cs *A, const cs *B, double alpha, double beta)
static int cs_wclear (int mark, int lemax, int *w, int n)
static int cs_diag (int i, int j, double aij, void *other)
int * cs_amd (const cs *A, int order)
static int cs_ereach (const cs *A, int k, const int *parent, int *s, int *w, double *x, int top)
csn * cs_chol (const cs *A, const css *S)
int cs_cholsol (const cs *A, double *b, int order)
static void cs_cedge (int j, int i, const int *first, int *maxfirst, int *delta, int *prevleaf, int *ancestor)
int * cs_counts (const cs *A, const int *parent, const int *post, int ata)
int cs_cumsum (int *p, int *c, int n)
int cs_dfs (int j, cs *L, int top, int *xi, int *pstack, const int *Pinv)
static int cs_bfs (const cs *A, int n, int *wi, int *wj, int *queue, const int *imatch, const int *jmatch, int mark)
static void cs_matched (int m, const int *wi, const int *jmatch, int *P, int *Q, int *cc, int *rr, int set, int mark)
static void cs_unmatched (int m, const int *wi, int *P, int *rr, int set)
static int cs_rprune (int i, int j, double aij, void *other)
csd * cs_dmperm (const cs *A)
static int cs_tol (int i, int j, double aij, void *tol)
int cs_droptol (cs *A, double tol)
static int cs_nonzero (int i, int j, double aij, void *other)
int cs_dropzeros (cs *A)
int cs_dupl (cs *A)
int cs_entry (cs *T, int i, int j, double x)
int * cs_etree (const cs *A, int ata)
int cs_fkeep (cs *A, int(*fkeep)(int, int, double, void *), void *other)
int cs_gaxpy (const cs *A, const double *x, double *y)
int cs_happly (const cs *V, int i, double beta, double *x)
double cs_house (double *x, double *beta, int n)
int cs_ipvec (int n, const int *P, const double *b, double *x)
cs * cs_load (FILE *f)
int cs_lsolve (const cs *L, double *x)
int cs_ltsolve (const cs *L, double *x)
csn * cs_lu (const cs *A, const css *S, double tol)
int cs_lusol (const cs *A, double *b, int order, double tol)
void * cs_malloc (int n, size_t size)
void * cs_calloc (int n, size_t size)
void * cs_free (void *p)
void * cs_realloc (void *p, int n, size_t size, int *ok)
static void cs_augment (int k, const cs *A, int *jmatch, int *cheap, int *w, int *js, int *is, int *ps)
int * cs_maxtrans (const cs *A)
cs * cs_multiply (const cs *A, const cs *B)
double cs_norm (const cs *A)
cs * cs_permute (const cs *A, const int *Pinv, const int *Q, int values)
int * cs_pinv (int const *P, int n)
int * cs_post (int n, const int *parent)
int cs_print (const cs *A, int brief)
int cs_pvec (int n, const int *P, const double *b, double *x)
csn * cs_qr (const cs *A, const css *S)
int cs_qrsol (const cs *A, double *b, int order)
int cs_reach (cs *L, const cs *B, int k, int *xi, const int *Pinv)
int cs_scatter (const cs *A, int j, double beta, int *w, double *x, int mark, cs *C, int nz)
csd * cs_scc (cs *A)
css * cs_schol (const cs *A, int order)
int cs_splsolve (cs *L, const cs *B, int k, int *xi, double *x, const int *Pinv)
static int * cs_vcount (const cs *A, const int *parent, int *m2, int *vnz)
css * cs_sqr (const cs *A, int order, int qr)
cs * cs_symperm (const cs *A, const int *Pinv, int values)
int cs_tdfs (int j, int k, int *head, const int *next, int *post, int *stack)
cs * cs_transpose (const cs *A, int values)
cs * cs_triplet (const cs *T)
int cs_updown (cs *L, int sigma, const cs *C, const int *parent)
int cs_usolve (const cs *U, double *x)
cs * cs_spalloc (int m, int n, int nzmax, int values, int triplet)
int cs_sprealloc (cs *A, int nzmax)
cs * cs_spfree (cs *A)
csn * cs_nfree (csn *N)
css * cs_sfree (css *S)
csd * cs_dalloc (int m, int n)
csd * cs_dfree (csd *D)
cs * cs_done (cs *C, void *w, void *x, int ok)
int * cs_idone (int *p, cs *C, void *w, int ok)
csn * cs_ndone (csn *N, cs *C, void *w, void *x, int ok)
csd * cs_ddone (csd *D, cs *C, void *w, int ok)
int cs_utsolve (const cs *U, double *x)
Function Documentation
cs* cs_add (const cs * A, const cs * B, double alpha, double beta)
Definition at line 8 of file csparse.c.
References cs_calloc(), cs_done(), cs_malloc(), cs_scatter(), cs_spalloc(), cs_sprealloc(), cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd().
static int cs_wclear (int mark, int lemax, int * w, int n) [static]
Definition at line 50 of file csparse.c.
Referenced by cs_amd().
static int cs_diag (int i, int j, double aij, void * other) [static]
Definition at line 73 of file csparse.c.
Referenced by cs_amd().
int* cs_amd (const cs * A, int order)
Definition at line 79 of file csparse.c.
References cs_add(), cs_diag(), cs_fkeep(), CS_FLIP, cs_idone(), cs_malloc(), CS_MAX, CS_MIN, cs_multiply(), cs_spfree(), cs_sprealloc(), cs_tdfs(), cs_transpose(), cs_wclear(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nzmax, and cs_sparse::p.
Referenced by cs_schol(), and cs_sqr().
static int cs_ereach (const cs * A, int k, const int * parent, int * s, int * w, double * x, int top) [static]
Definition at line 453 of file csparse.c.
References cs_sparse::i, cs_sparse::p, and cs_sparse::x.
Referenced by cs_chol().
csn* cs_chol (const cs * A, const css * S)
Definition at line 474 of file csparse.c.
References cs_symbolic::cp, cs_calloc(), cs_ereach(), cs_malloc(), cs_ndone(), cs_spalloc(), cs_symperm(), cs_sparse::i, cs_numeric::L, cs_sparse::n, cs_sparse::p, cs_symbolic::parent, cs_symbolic::Pinv, and cs_sparse::x.
Referenced by cs_cholsol().
int cs_cholsol (const cs * A, double * b, int order)
Definition at line 533 of file csparse.c.
References cs_chol(), cs_free(), cs_ipvec(), cs_lsolve(), cs_ltsolve(), cs_malloc(), cs_nfree(), cs_pvec(), cs_schol(), cs_sfree(), cs_numeric::L, cs_sparse::n, and cs_symbolic::Pinv.
static void cs_cedge (int j, int i, const int * first, int * maxfirst, int * delta, int * prevleaf, int * ancestor) [static]
Definition at line 559 of file csparse.c.
Referenced by cs_counts().
int* cs_counts (const cs * A, const int * parent, const int * post, int ata)
Definition at line 582 of file csparse.c.
References cs_cedge(), cs_idone(), cs_malloc(), CS_MIN, cs_transpose(), cs_sparse::i, cs_sparse::m, cs_sparse::n, and cs_sparse::p.
Referenced by cs_schol(), and cs_sqr().
int cs_cumsum (int * p, int * c, int n)
Definition at line 651 of file csparse.c.
Referenced by cs_schol(), cs_symperm(), cs_transpose(), and cs_triplet().
int cs_dfs (int j, cs * L, int top, int * xi, int * pstack, const int * Pinv)
Definition at line 666 of file csparse.c.
References CS_MARK, CS_MARKED, CS_UNFLIP, cs_sparse::i, and cs_sparse::p.
Referenced by cs_reach(), and cs_scc().
static int cs_bfs (const cs * A, int n, int * wi, int * wj, int * queue, const int * imatch, const int * jmatch, int mark) [static]
Definition at line 703 of file csparse.c.
References cs_spfree(), cs_transpose(), cs_sparse::i, and cs_sparse::p.
Referenced by cs_dmperm().
static void cs_matched (int m, const int * wi, const int * jmatch, int * P, int * Q, int * cc, int * rr, int set, int mark) [static]
Definition at line 738 of file csparse.c.
Referenced by cs_dmperm().
static void cs_unmatched (int m, const int * wi, int * P, int * rr, int set) [static]
Definition at line 754 of file csparse.c.
Referenced by cs_dmperm().
static int cs_rprune (int i, int j, double aij, void * other) [static]
Definition at line 767 of file csparse.c.
Referenced by cs_dmperm().
csd* cs_dmperm (const cs * A)
Definition at line 774 of file csparse.c.
References cs_dmperm_results::cc, cs_bfs(), cs_dalloc(), cs_ddone(), cs_dfree(), cs_fkeep(), cs_free(), cs_matched(), cs_maxtrans(), cs_permute(), cs_pinv(), cs_rprune(), cs_scc(), cs_unmatched(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_dmperm_results::nb, cs_sparse::p, cs_dmperm_results::P, cs_dmperm_results::Q, cs_dmperm_results::R, cs_dmperm_results::rr, and cs_dmperm_results::S.
static int cs_tol (int i, int j, double aij, void * tol) [static]
Definition at line 860 of file csparse.c.
Referenced by cs_droptol().
int cs_droptol (cs * A, double tol)
Definition at line 864 of file csparse.c.
References cs_fkeep(), and cs_tol().
static int cs_nonzero (int i, int j, double aij, void * other) [static]
Definition at line 869 of file csparse.c.
Referenced by cs_dropzeros().
int cs_dropzeros (cs * A)
Definition at line 873 of file csparse.c.
References cs_fkeep(), and cs_nonzero().
int cs_dupl (cs * A)
Definition at line 877 of file csparse.c.
References cs_free(), cs_malloc(), cs_sprealloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
int cs_entry (cs * T, int i, int j, double x)
Definition at line 926 of file csparse.c.
References CS_MAX, cs_sprealloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nz, cs_sparse::nzmax, cs_sparse::p, and cs_sparse::x.
Referenced by cs_load().
int* cs_etree (const cs * A, int ata)
Definition at line 938 of file csparse.c.
References cs_idone(), cs_malloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, and cs_sparse::p.
Referenced by cs_schol(), and cs_sqr().
int cs_fkeep (cs * A, int(*)(int, int, double, void *) fkeep, void * other)
Definition at line 972 of file csparse.c.
References cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd(), cs_dmperm(), cs_droptol(), and cs_dropzeros().
int cs_gaxpy (const cs * A, const double * x, double * y)
Definition at line 998 of file csparse.c.
References cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by fclib_merit_local().
int cs_happly (const cs * V, int i, double beta, double * x)
Definition at line 1018 of file csparse.c.
References cs_sparse::i, cs_sparse::p, and cs_sparse::x.
Referenced by cs_qr(), and cs_qrsol().
double cs_house (double * x, double * beta, int n)
Definition at line 1040 of file csparse.c.
Referenced by cs_qr().
int cs_ipvec (int n, const int * P, const double * b, double * x)
Definition at line 1062 of file csparse.c.
Referenced by cs_cholsol(), cs_lusol(), and cs_qrsol().
cs* cs_load (FILE * f)
Definition at line 1069 of file csparse.c.
References cs_entry(), cs_spalloc(), and cs_spfree().
int cs_lsolve (const cs * L, double * x)
Definition at line 1093 of file csparse.c.
References cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_cholsol(), and cs_lusol().
int cs_ltsolve (const cs * L, double * x)
Definition at line 1127 of file csparse.c.
References cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_cholsol().
csn* cs_lu (const cs * A, const css * S, double tol)
Definition at line 1163 of file csparse.c.
References cs_calloc(), cs_malloc(), cs_ndone(), cs_spalloc(), cs_splsolve(), cs_sprealloc(), cs_sparse::i, cs_numeric::L, cs_symbolic::lnz, cs_sparse::n, cs_sparse::nzmax, cs_sparse::p, cs_numeric::Pinv, cs_symbolic::Q, cs_numeric::U, cs_symbolic::unz, and cs_sparse::x.
Referenced by cs_lusol().
int cs_lusol (const cs * A, double * b, int order, double tol)
Definition at line 1255 of file csparse.c.
References cs_free(), cs_ipvec(), cs_lsolve(), cs_lu(), cs_malloc(), cs_nfree(), cs_sfree(), cs_sqr(), cs_usolve(), cs_numeric::L, cs_sparse::n, cs_numeric::Pinv, cs_symbolic::Q, and cs_numeric::U.
void* cs_malloc (int n, size_t size)
Definition at line 1288 of file csparse.c.
References CS_MAX, and CS_OVERFLOW.
Referenced by cs_add(), cs_amd(), cs_chol(), cs_cholsol(), cs_counts(), cs_dalloc(), cs_dupl(), cs_etree(), cs_lu(), cs_lusol(), cs_maxtrans(), cs_multiply(), cs_pinv(), cs_post(), cs_qr(), cs_scc(), cs_schol(), cs_spalloc(), cs_updown(), and cs_vcount().
void* cs_calloc (int n, size_t size)
Definition at line 1294 of file csparse.c.
References CS_MAX, and CS_OVERFLOW.
Referenced by cs_add(), cs_chol(), cs_dalloc(), cs_lu(), cs_maxtrans(), cs_multiply(), cs_qr(), cs_qrsol(), cs_schol(), cs_spalloc(), cs_sqr(), cs_symperm(), cs_transpose(), and cs_triplet().
void* cs_free (void * p)
Definition at line 1300 of file csparse.c.
Referenced by cs_cholsol(), cs_ddone(), cs_dfree(), cs_dmperm(), cs_done(), cs_dupl(), cs_idone(), cs_lusol(), cs_ndone(), cs_nfree(), cs_qrsol(), cs_schol(), cs_sfree(), cs_spfree(), cs_sqr(), and cs_updown().
void* cs_realloc (void * p, int n, size_t size, int * ok)
Definition at line 1307 of file csparse.c.
References CS_MAX, and CS_OVERFLOW.
Referenced by cs_sprealloc().
static void cs_augment (int k, const cs * A, int * jmatch, int * cheap, int * w, int * js, int * is, int * ps) [static]
Definition at line 1318 of file csparse.c.
References cs_sparse::i, and cs_sparse::p.
Referenced by cs_maxtrans().
int* cs_maxtrans (const cs * A)
Definition at line 1359 of file csparse.c.
References cs_augment(), cs_calloc(), cs_idone(), cs_malloc(), cs_transpose(), cs_sparse::i, cs_sparse::m, cs_sparse::n, and cs_sparse::p.
Referenced by cs_dmperm().
cs* cs_multiply (const cs * A, const cs * B)
Definition at line 1400 of file csparse.c.
References cs_calloc(), cs_done(), cs_malloc(), cs_scatter(), cs_spalloc(), cs_sprealloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd().
double cs_norm (const cs * A)
Definition at line 1440 of file csparse.c.
References CS_MAX, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_print().
cs* cs_permute (const cs * A, const int * Pinv, const int * Q, int values)
Definition at line 1457 of file csparse.c.
References cs_done(), cs_spalloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_dmperm(), and cs_sqr().
int* cs_pinv (int const * P, int n)
Definition at line 1488 of file csparse.c.
References cs_malloc().
Referenced by cs_dmperm(), and cs_schol().
int* cs_post (int n, const int * parent)
Definition at line 1499 of file csparse.c.
References cs_idone(), cs_malloc(), and cs_tdfs().
Referenced by cs_schol(), and cs_sqr().
int cs_print (const cs * A, int brief)
Definition at line 1525 of file csparse.c.
References CS_COPYRIGHT, CS_DATE, cs_norm(), CS_SUBSUB, CS_SUBVER, CS_VER, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nz, cs_sparse::nzmax, cs_sparse::p, and cs_sparse::x.
int cs_pvec (int n, const int * P, const double * b, double * x)
Definition at line 1578 of file csparse.c.
Referenced by cs_cholsol(), and cs_qrsol().
csn* cs_qr (const cs * A, const css * S)
Definition at line 1587 of file csparse.c.
References cs_numeric::B, cs_calloc(), cs_happly(), cs_house(), cs_malloc(), cs_ndone(), cs_scatter(), cs_spalloc(), cs_sparse::i, cs_numeric::L, cs_symbolic::lnz, cs_sparse::m, cs_symbolic::m2, cs_sparse::n, cs_sparse::p, cs_symbolic::parent, cs_symbolic::Pinv, cs_symbolic::Q, cs_numeric::U, cs_symbolic::unz, and cs_sparse::x.
Referenced by cs_qrsol().
int cs_qrsol (const cs * A, double * b, int order)
Definition at line 1674 of file csparse.c.
References cs_numeric::B, cs_calloc(), cs_free(), cs_happly(), cs_ipvec(), cs_nfree(), cs_pvec(), cs_qr(), cs_sfree(), cs_spfree(), cs_sqr(), cs_transpose(), cs_usolve(), cs_utsolve(), cs_numeric::L, cs_sparse::m, cs_symbolic::m2, cs_sparse::n, cs_symbolic::Pinv, cs_symbolic::Q, and cs_numeric::U.
int cs_reach (cs * L, const cs * B, int k, int * xi, const int * Pinv)
Definition at line 1728 of file csparse.c.
References cs_dfs(), CS_MARK, CS_MARKED, cs_sparse::i, cs_sparse::n, and cs_sparse::p.
Referenced by cs_splsolve().
int cs_scatter (const cs * A, int j, double beta, int * w, double * x, int mark, cs * C, int nz)
Definition at line 1749 of file csparse.c.
References cs_sparse::i, cs_sparse::p, and cs_sparse::x.
Referenced by cs_add(), cs_multiply(), and cs_qr().
csd* cs_scc (cs * A)
Definition at line 1774 of file csparse.c.
References cs_dalloc(), cs_ddone(), cs_dfs(), cs_malloc(), CS_MARK, CS_MARKED, cs_transpose(), cs_sparse::n, cs_dmperm_results::nb, cs_sparse::p, cs_dmperm_results::P, and cs_dmperm_results::R.
Referenced by cs_dmperm().
css* cs_schol (const cs * A, int order)
Definition at line 1812 of file csparse.c.
References cs_symbolic::cp, cs_amd(), cs_calloc(), cs_counts(), cs_cumsum(), cs_etree(), cs_free(), cs_malloc(), cs_pinv(), cs_post(), cs_sfree(), cs_spfree(), cs_symperm(), cs_symbolic::lnz, cs_sparse::n, cs_symbolic::parent, cs_symbolic::Pinv, and cs_symbolic::unz.
Referenced by cs_cholsol().
int cs_splsolve (cs * L, const cs * B, int k, int * xi, double * x, const int * Pinv)
Definition at line 1838 of file csparse.c.
References cs_reach(), cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_lu().
static int* cs_vcount (const cs * A, const int * parent, int * m2, int * vnz) [static]
Definition at line 1867 of file csparse.c.
References cs_idone(), cs_malloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, and cs_sparse::p.
Referenced by cs_sqr().
css* cs_sqr (const cs * A, int order, int qr)
Definition at line 1917 of file csparse.c.
References cs_symbolic::cp, cs_amd(), cs_calloc(), cs_counts(), cs_etree(), cs_free(), cs_permute(), cs_post(), cs_sfree(), cs_spfree(), cs_vcount(), cs_symbolic::lnz, cs_symbolic::m2, cs_sparse::n, cs_sparse::p, cs_symbolic::parent, cs_symbolic::Pinv, cs_symbolic::Q, and cs_symbolic::unz.
Referenced by cs_lusol(), and cs_qrsol().
cs* cs_symperm (const cs * A, const int * Pinv, int values)
Definition at line 1949 of file csparse.c.
References cs_calloc(), cs_cumsum(), cs_done(), CS_MAX, CS_MIN, cs_spalloc(), cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_chol(), and cs_schol().
int cs_tdfs (int j, int k, int * head, const int * next, int * post, int * stack)
Definition at line 1993 of file csparse.c.
Referenced by cs_amd(), and cs_post().
cs* cs_transpose (const cs * A, int values)
Definition at line 2017 of file csparse.c.
References cs_calloc(), cs_cumsum(), cs_done(), cs_spalloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd(), cs_bfs(), cs_counts(), cs_maxtrans(), cs_qrsol(), cs_scc(), and fclib_merit_local().
cs* cs_triplet (const cs * T)
Definition at line 2048 of file csparse.c.
References cs_calloc(), cs_cumsum(), cs_done(), cs_spalloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nz, cs_sparse::p, and cs_sparse::x.
int cs_updown (cs * L, int sigma, const cs * C, const int * parent)
Definition at line 2077 of file csparse.c.
References cs_free(), cs_malloc(), CS_MIN, cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
int cs_usolve (const cs * U, double * x)
Definition at line 2119 of file csparse.c.
References cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_lusol(), and cs_qrsol().
cs* cs_spalloc (int m, int n, int nzmax, int values, int triplet)
Definition at line 2140 of file csparse.c.
References cs_calloc(), cs_malloc(), CS_MAX, cs_spfree(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nz, cs_sparse::nzmax, cs_sparse::p, and cs_sparse::x.
Referenced by cs_add(), cs_chol(), cs_load(), cs_lu(), cs_multiply(), cs_permute(), cs_qr(), cs_symperm(), cs_transpose(), and cs_triplet().
int cs_sprealloc (cs * A, int nzmax)
Definition at line 2155 of file csparse.c.
References cs_realloc(), cs_sparse::i, cs_sparse::n, cs_sparse::nz, cs_sparse::nzmax, cs_sparse::p, and cs_sparse::x.
Referenced by cs_add(), cs_amd(), cs_dupl(), cs_entry(), cs_lu(), and cs_multiply().
cs* cs_spfree (cs * A)
Definition at line 2169 of file csparse.c.
References cs_free(), cs_sparse::i, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd(), cs_bfs(), cs_ddone(), cs_done(), cs_idone(), cs_load(), cs_ndone(), cs_nfree(), cs_qrsol(), cs_schol(), cs_spalloc(), and cs_sqr().
csn* cs_nfree (csn * N)
Definition at line 2179 of file csparse.c.
References cs_numeric::B, cs_free(), cs_spfree(), cs_numeric::L, cs_numeric::Pinv, and cs_numeric::U.
Referenced by cs_cholsol(), cs_lusol(), cs_ndone(), and cs_qrsol().
css* cs_sfree (css * S)
Definition at line 2190 of file csparse.c.
References cs_symbolic::cp, cs_free(), cs_symbolic::parent, cs_symbolic::Pinv, and cs_symbolic::Q.
Referenced by cs_cholsol(), cs_lusol(), cs_qrsol(), cs_schol(), and cs_sqr().
csd* cs_dalloc (int m, int n)
Definition at line 2201 of file csparse.c.
References cs_calloc(), cs_dfree(), cs_malloc(), cs_dmperm_results::P, cs_dmperm_results::Q, cs_dmperm_results::R, and cs_dmperm_results::S.
Referenced by cs_dmperm(), and cs_scc().
csd* cs_dfree (csd * D)
Definition at line 2214 of file csparse.c.
References cs_free(), cs_dmperm_results::P, cs_dmperm_results::Q, cs_dmperm_results::R, and cs_dmperm_results::S.
Referenced by cs_dalloc(), cs_ddone(), and cs_dmperm().
cs* cs_done (cs * C, void * w, void * x, int ok)
Definition at line 2225 of file csparse.c.
References cs_free(), and cs_spfree().
Referenced by cs_add(), cs_multiply(), cs_permute(), cs_symperm(), cs_transpose(), and cs_triplet().
int* cs_idone (int * p, cs * C, void * w, int ok)
Definition at line 2233 of file csparse.c.
References cs_free(), and cs_spfree().
Referenced by cs_amd(), cs_counts(), cs_etree(), cs_maxtrans(), cs_post(), and cs_vcount().
csn* cs_ndone (csn * N, cs * C, void * w, void * x, int ok)
Definition at line 2241 of file csparse.c.
References cs_free(), cs_nfree(), and cs_spfree().
Referenced by cs_chol(), cs_lu(), and cs_qr().
csd* cs_ddone (csd * D, cs * C, void * w, int ok)
Definition at line 2250 of file csparse.c.
References cs_dfree(), cs_free(), and cs_spfree().
Referenced by cs_dmperm(), and cs_scc().
int cs_utsolve (const cs * U, double * x)
Definition at line 2258 of file csparse.c.
References cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_qrsol().