csparse.h File Reference
Classes
struct cs_sparse
struct cs_symbolic
struct cs_numeric
struct cs_dmperm_results
Macros
#define CS_VER 1		    /* CSparse Version 1.2.0 */
#define CS_SUBVER 2
#define CS_SUBSUB 0
#define CS_DATE `Mar 6, 2006`	    /* CSparse release date */
#define CS_COPYRIGHT `Copyright (c) Timothy A. Davis, 2006`
#define CS_MAX(a, b) (((a) > (b)) ? (a) : (b))
#define CS_MIN(a, b) (((a) < (b)) ? (a) : (b))
#define CS_FLIP(i) (-(i)-2)
#define CS_UNFLIP(i) (((i) < 0) ? CS_FLIP(i) : (i))
#define CS_MARKED(Ap, j) (Ap [j] < 0)
#define CS_MARK(Ap, j) { Ap [j] = CS_FLIP (Ap [j]) ; }
#define CS_OVERFLOW(n, size) (n > INT_MAX / (int) size)
Typedefs
typedef struct cs_sparse cs
typedef struct cs_symbolic css
typedef struct cs_numeric csn
typedef struct cs_dmperm_results csd
Functions
cs * cs_add (const cs *A, const cs *B, double alpha, double beta)
int cs_cholsol (const cs *A, double *b, int order)
int cs_dupl (cs *A)
int cs_entry (cs *T, int i, int j, double x)
int cs_lusol (const cs *A, double *b, int order, double tol)
int cs_gaxpy (const cs *A, const double *x, double *y)
cs * cs_multiply (const cs *A, const cs *B)
int cs_qrsol (const cs *A, double *b, int order)
cs * cs_transpose (const cs *A, int values)
cs * cs_triplet (const cs *T)
double cs_norm (const cs *A)
int cs_print (const cs *A, int brief)
cs * cs_load (FILE *f)
void * cs_calloc (int n, size_t size)
void * cs_free (void *p)
void * cs_realloc (void *p, int n, size_t size, int *ok)
cs * cs_spalloc (int m, int n, int nzmax, int values, int triplet)
cs * cs_spfree (cs *A)
int cs_sprealloc (cs *A, int nzmax)
void * cs_malloc (int n, size_t size)
int * cs_amd (const cs *A, int order)
csn * cs_chol (const cs *A, const css *S)
csd * cs_dmperm (const cs *A)
int cs_droptol (cs *A, double tol)
int cs_dropzeros (cs *A)
int cs_happly (const cs *V, int i, double beta, double *x)
int cs_ipvec (int n, const int *P, const double *b, double *x)
int cs_lsolve (const cs *L, double *x)
int cs_ltsolve (const cs *L, double *x)
csn * cs_lu (const cs *A, const css *S, double tol)
cs * cs_permute (const cs *A, const int *P, const int *Q, int values)
int * cs_pinv (const int *P, int n)
int cs_pvec (int n, const int *P, const double *b, double *x)
csn * cs_qr (const cs *A, const css *S)
css * cs_schol (const cs *A, int order)
css * cs_sqr (const cs *A, int order, int qr)
cs * cs_symperm (const cs *A, const int *Pinv, int values)
int cs_usolve (const cs *U, double *x)
int cs_utsolve (const cs *U, double *x)
int cs_updown (cs *L, int sigma, const cs *C, const int *parent)
css * cs_sfree (css *S)
csn * cs_nfree (csn *N)
csd * cs_dfree (csd *D)
int * cs_counts (const cs *A, const int *parent, const int *post, int ata)
int cs_cumsum (int *p, int *c, int n)
int cs_dfs (int j, cs *L, int top, int *xi, int *pstack, const int *Pinv)
int * cs_etree (const cs *A, int ata)
int cs_fkeep (cs *A, int(*fkeep)(int, int, double, void *), void *other)
double cs_house (double *x, double *beta, int n)
int * cs_maxtrans (const cs *A)
int * cs_post (int n, const int *parent)
int cs_reach (cs *L, const cs *B, int k, int *xi, const int *Pinv)
csd * cs_scc (cs *A)
int cs_scatter (const cs *A, int j, double beta, int *w, double *x, int mark, cs *C, int nz)
int cs_splsolve (cs *L, const cs *B, int k, int *xi, double *x, const int *Pinv)
int cs_tdfs (int j, int k, int *head, const int *next, int *post, int *stack)
csd * cs_dalloc (int m, int n)
cs * cs_done (cs *C, void *w, void *x, int ok)
int * cs_idone (int *p, cs *C, void *w, int ok)
csn * cs_ndone (csn *N, cs *C, void *w, void *x, int ok)
csd * cs_ddone (csd *D, cs *C, void *w, int ok)
Macro Definition Documentation
#define CS_VER 1		    /* CSparse Version 1.2.0 */
Definition at line 7 of file csparse.h.
Referenced by cs_print().
#define CS_SUBVER 2
Definition at line 8 of file csparse.h.
Referenced by cs_print().
#define CS_SUBSUB 0
Definition at line 9 of file csparse.h.
Referenced by cs_print().
#define CS_DATE `Mar 6, 2006`	    /* CSparse release date */
Definition at line 10 of file csparse.h.
Referenced by cs_print().
#define CS_COPYRIGHT `Copyright (c) Timothy A. Davis, 2006`
Definition at line 11 of file csparse.h.
Referenced by cs_print().
#define CS_MAX(a, b) (((a) > (b)) ? (a) : (b))
Definition at line 127 of file csparse.h.
Referenced by cs_amd(), cs_calloc(), cs_entry(), cs_malloc(), cs_norm(), cs_realloc(), cs_spalloc(), and cs_symperm().
#define CS_MIN(a, b) (((a) < (b)) ? (a) : (b))
Definition at line 128 of file csparse.h.
Referenced by cs_amd(), cs_counts(), cs_symperm(), and cs_updown().
#define CS_FLIP(i) (-(i)-2)
Definition at line 129 of file csparse.h.
Referenced by cs_amd().
#define CS_UNFLIP(i) (((i) < 0) ? CS_FLIP(i) : (i))
Definition at line 130 of file csparse.h.
Referenced by cs_dfs().
#define CS_MARKED(Ap, j) (Ap [j] < 0)
Definition at line 131 of file csparse.h.
Referenced by cs_dfs(), cs_reach(), and cs_scc().
#define CS_MARK(Ap, j) { Ap [j] = CS_FLIP (Ap [j]) ; }
Definition at line 132 of file csparse.h.
Referenced by cs_dfs(), cs_reach(), and cs_scc().
#define CS_OVERFLOW(n, size) (n > INT_MAX / (int) size)
Definition at line 133 of file csparse.h.
Referenced by cs_calloc(), cs_malloc(), and cs_realloc().
Typedef Documentation
typedef struct cs_sparse cs
typedef struct cs_symbolic css
typedef struct cs_numeric csn
typedef struct cs_dmperm_results csd
Function Documentation
cs* cs_add (const cs * A, const cs * B, double alpha, double beta)
Definition at line 8 of file csparse.c.
References cs_calloc(), cs_done(), cs_malloc(), cs_scatter(), cs_spalloc(), cs_sprealloc(), cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd().
int cs_cholsol (const cs * A, double * b, int order)
Definition at line 533 of file csparse.c.
References cs_chol(), cs_free(), cs_ipvec(), cs_lsolve(), cs_ltsolve(), cs_malloc(), cs_nfree(), cs_pvec(), cs_schol(), cs_sfree(), cs_numeric::L, cs_sparse::n, and cs_symbolic::Pinv.
int cs_dupl (cs * A)
Definition at line 877 of file csparse.c.
References cs_free(), cs_malloc(), cs_sprealloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
int cs_entry (cs * T, int i, int j, double x)
Definition at line 926 of file csparse.c.
References CS_MAX, cs_sprealloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nz, cs_sparse::nzmax, cs_sparse::p, and cs_sparse::x.
Referenced by cs_load().
int cs_lusol (const cs * A, double * b, int order, double tol)
Definition at line 1255 of file csparse.c.
References cs_free(), cs_ipvec(), cs_lsolve(), cs_lu(), cs_malloc(), cs_nfree(), cs_sfree(), cs_sqr(), cs_usolve(), cs_numeric::L, cs_sparse::n, cs_numeric::Pinv, cs_symbolic::Q, and cs_numeric::U.
int cs_gaxpy (const cs * A, const double * x, double * y)
Definition at line 998 of file csparse.c.
References cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by fclib_merit_local().
cs* cs_multiply (const cs * A, const cs * B)
Definition at line 1400 of file csparse.c.
References cs_calloc(), cs_done(), cs_malloc(), cs_scatter(), cs_spalloc(), cs_sprealloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd().
int cs_qrsol (const cs * A, double * b, int order)
Definition at line 1674 of file csparse.c.
References cs_numeric::B, cs_calloc(), cs_free(), cs_happly(), cs_ipvec(), cs_nfree(), cs_pvec(), cs_qr(), cs_sfree(), cs_spfree(), cs_sqr(), cs_transpose(), cs_usolve(), cs_utsolve(), cs_numeric::L, cs_sparse::m, cs_symbolic::m2, cs_sparse::n, cs_symbolic::Pinv, cs_symbolic::Q, and cs_numeric::U.
cs* cs_transpose (const cs * A, int values)
Definition at line 2017 of file csparse.c.
References cs_calloc(), cs_cumsum(), cs_done(), cs_spalloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd(), cs_bfs(), cs_counts(), cs_maxtrans(), cs_qrsol(), cs_scc(), and fclib_merit_local().
cs* cs_triplet (const cs * T)
Definition at line 2048 of file csparse.c.
References cs_calloc(), cs_cumsum(), cs_done(), cs_spalloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nz, cs_sparse::p, and cs_sparse::x.
double cs_norm (const cs * A)
Definition at line 1440 of file csparse.c.
References CS_MAX, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_print().
int cs_print (const cs * A, int brief)
Definition at line 1525 of file csparse.c.
References CS_COPYRIGHT, CS_DATE, cs_norm(), CS_SUBSUB, CS_SUBVER, CS_VER, cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nz, cs_sparse::nzmax, cs_sparse::p, and cs_sparse::x.
cs* cs_load (FILE * f)
Definition at line 1069 of file csparse.c.
References cs_entry(), cs_spalloc(), and cs_spfree().
void* cs_calloc (int n, size_t size)
Definition at line 1294 of file csparse.c.
References CS_MAX, and CS_OVERFLOW.
Referenced by cs_add(), cs_chol(), cs_dalloc(), cs_lu(), cs_maxtrans(), cs_multiply(), cs_qr(), cs_qrsol(), cs_schol(), cs_spalloc(), cs_sqr(), cs_symperm(), cs_transpose(), and cs_triplet().
void* cs_free (void * p)
Definition at line 1300 of file csparse.c.
Referenced by cs_cholsol(), cs_ddone(), cs_dfree(), cs_dmperm(), cs_done(), cs_dupl(), cs_idone(), cs_lusol(), cs_ndone(), cs_nfree(), cs_qrsol(), cs_schol(), cs_sfree(), cs_spfree(), cs_sqr(), and cs_updown().
void* cs_realloc (void * p, int n, size_t size, int * ok)
Definition at line 1307 of file csparse.c.
References CS_MAX, and CS_OVERFLOW.
Referenced by cs_sprealloc().
cs* cs_spalloc (int m, int n, int nzmax, int values, int triplet)
Definition at line 2140 of file csparse.c.
References cs_calloc(), cs_malloc(), CS_MAX, cs_spfree(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nz, cs_sparse::nzmax, cs_sparse::p, and cs_sparse::x.
Referenced by cs_add(), cs_chol(), cs_load(), cs_lu(), cs_multiply(), cs_permute(), cs_qr(), cs_symperm(), cs_transpose(), and cs_triplet().
cs* cs_spfree (cs * A)
Definition at line 2169 of file csparse.c.
References cs_free(), cs_sparse::i, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd(), cs_bfs(), cs_ddone(), cs_done(), cs_idone(), cs_load(), cs_ndone(), cs_nfree(), cs_qrsol(), cs_schol(), cs_spalloc(), and cs_sqr().
int cs_sprealloc (cs * A, int nzmax)
Definition at line 2155 of file csparse.c.
References cs_realloc(), cs_sparse::i, cs_sparse::n, cs_sparse::nz, cs_sparse::nzmax, cs_sparse::p, and cs_sparse::x.
Referenced by cs_add(), cs_amd(), cs_dupl(), cs_entry(), cs_lu(), and cs_multiply().
void* cs_malloc (int n, size_t size)
Definition at line 1288 of file csparse.c.
References CS_MAX, and CS_OVERFLOW.
Referenced by cs_add(), cs_amd(), cs_chol(), cs_cholsol(), cs_counts(), cs_dalloc(), cs_dupl(), cs_etree(), cs_lu(), cs_lusol(), cs_maxtrans(), cs_multiply(), cs_pinv(), cs_post(), cs_qr(), cs_scc(), cs_schol(), cs_spalloc(), cs_updown(), and cs_vcount().
int* cs_amd (const cs * A, int order)
Definition at line 79 of file csparse.c.
References cs_add(), cs_diag(), cs_fkeep(), CS_FLIP, cs_idone(), cs_malloc(), CS_MAX, CS_MIN, cs_multiply(), cs_spfree(), cs_sprealloc(), cs_tdfs(), cs_transpose(), cs_wclear(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::nzmax, and cs_sparse::p.
Referenced by cs_schol(), and cs_sqr().
csn* cs_chol (const cs * A, const css * S)
Definition at line 474 of file csparse.c.
References cs_symbolic::cp, cs_calloc(), cs_ereach(), cs_malloc(), cs_ndone(), cs_spalloc(), cs_symperm(), cs_sparse::i, cs_numeric::L, cs_sparse::n, cs_sparse::p, cs_symbolic::parent, cs_symbolic::Pinv, and cs_sparse::x.
Referenced by cs_cholsol().
csd* cs_dmperm (const cs * A)
Definition at line 774 of file csparse.c.
References cs_dmperm_results::cc, cs_bfs(), cs_dalloc(), cs_ddone(), cs_dfree(), cs_fkeep(), cs_free(), cs_matched(), cs_maxtrans(), cs_permute(), cs_pinv(), cs_rprune(), cs_scc(), cs_unmatched(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_dmperm_results::nb, cs_sparse::p, cs_dmperm_results::P, cs_dmperm_results::Q, cs_dmperm_results::R, cs_dmperm_results::rr, and cs_dmperm_results::S.
int cs_droptol (cs * A, double tol)
Definition at line 864 of file csparse.c.
References cs_fkeep(), and cs_tol().
int cs_dropzeros (cs * A)
Definition at line 873 of file csparse.c.
References cs_fkeep(), and cs_nonzero().
int cs_happly (const cs * V, int i, double beta, double * x)
Definition at line 1018 of file csparse.c.
References cs_sparse::i, cs_sparse::p, and cs_sparse::x.
Referenced by cs_qr(), and cs_qrsol().
int cs_ipvec (int n, const int * P, const double * b, double * x)
Definition at line 1062 of file csparse.c.
Referenced by cs_cholsol(), cs_lusol(), and cs_qrsol().
int cs_lsolve (const cs * L, double * x)
Definition at line 1093 of file csparse.c.
References cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_cholsol(), and cs_lusol().
int cs_ltsolve (const cs * L, double * x)
Definition at line 1127 of file csparse.c.
References cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_cholsol().
csn* cs_lu (const cs * A, const css * S, double tol)
Definition at line 1163 of file csparse.c.
References cs_calloc(), cs_malloc(), cs_ndone(), cs_spalloc(), cs_splsolve(), cs_sprealloc(), cs_sparse::i, cs_numeric::L, cs_symbolic::lnz, cs_sparse::n, cs_sparse::nzmax, cs_sparse::p, cs_numeric::Pinv, cs_symbolic::Q, cs_numeric::U, cs_symbolic::unz, and cs_sparse::x.
Referenced by cs_lusol().
cs* cs_permute (const cs * A, const int * P, const int * Q, int values)
Definition at line 1457 of file csparse.c.
References cs_done(), cs_spalloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_dmperm(), and cs_sqr().
int* cs_pinv (const int * P, int n)
Definition at line 1488 of file csparse.c.
References cs_malloc().
Referenced by cs_dmperm(), and cs_schol().
int cs_pvec (int n, const int * P, const double * b, double * x)
Definition at line 1578 of file csparse.c.
Referenced by cs_cholsol(), and cs_qrsol().
csn* cs_qr (const cs * A, const css * S)
Definition at line 1587 of file csparse.c.
References cs_numeric::B, cs_calloc(), cs_happly(), cs_house(), cs_malloc(), cs_ndone(), cs_scatter(), cs_spalloc(), cs_sparse::i, cs_numeric::L, cs_symbolic::lnz, cs_sparse::m, cs_symbolic::m2, cs_sparse::n, cs_sparse::p, cs_symbolic::parent, cs_symbolic::Pinv, cs_symbolic::Q, cs_numeric::U, cs_symbolic::unz, and cs_sparse::x.
Referenced by cs_qrsol().
css* cs_schol (const cs * A, int order)
Definition at line 1812 of file csparse.c.
References cs_symbolic::cp, cs_amd(), cs_calloc(), cs_counts(), cs_cumsum(), cs_etree(), cs_free(), cs_malloc(), cs_pinv(), cs_post(), cs_sfree(), cs_spfree(), cs_symperm(), cs_symbolic::lnz, cs_sparse::n, cs_symbolic::parent, cs_symbolic::Pinv, and cs_symbolic::unz.
Referenced by cs_cholsol().
css* cs_sqr (const cs * A, int order, int qr)
Definition at line 1917 of file csparse.c.
References cs_symbolic::cp, cs_amd(), cs_calloc(), cs_counts(), cs_etree(), cs_free(), cs_permute(), cs_post(), cs_sfree(), cs_spfree(), cs_vcount(), cs_symbolic::lnz, cs_symbolic::m2, cs_sparse::n, cs_sparse::p, cs_symbolic::parent, cs_symbolic::Pinv, cs_symbolic::Q, and cs_symbolic::unz.
Referenced by cs_lusol(), and cs_qrsol().
cs* cs_symperm (const cs * A, const int * Pinv, int values)
Definition at line 1949 of file csparse.c.
References cs_calloc(), cs_cumsum(), cs_done(), CS_MAX, CS_MIN, cs_spalloc(), cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_chol(), and cs_schol().
int cs_usolve (const cs * U, double * x)
Definition at line 2119 of file csparse.c.
References cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_lusol(), and cs_qrsol().
int cs_utsolve (const cs * U, double * x)
Definition at line 2258 of file csparse.c.
References cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_qrsol().
int cs_updown (cs * L, int sigma, const cs * C, const int * parent)
Definition at line 2077 of file csparse.c.
References cs_free(), cs_malloc(), CS_MIN, cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
css* cs_sfree (css * S)
Definition at line 2190 of file csparse.c.
References cs_symbolic::cp, cs_free(), cs_symbolic::parent, cs_symbolic::Pinv, and cs_symbolic::Q.
Referenced by cs_cholsol(), cs_lusol(), cs_qrsol(), cs_schol(), and cs_sqr().
csn* cs_nfree (csn * N)
Definition at line 2179 of file csparse.c.
References cs_numeric::B, cs_free(), cs_spfree(), cs_numeric::L, cs_numeric::Pinv, and cs_numeric::U.
Referenced by cs_cholsol(), cs_lusol(), cs_ndone(), and cs_qrsol().
csd* cs_dfree (csd * D)
Definition at line 2214 of file csparse.c.
References cs_free(), cs_dmperm_results::P, cs_dmperm_results::Q, cs_dmperm_results::R, and cs_dmperm_results::S.
Referenced by cs_dalloc(), cs_ddone(), and cs_dmperm().
int* cs_counts (const cs * A, const int * parent, const int * post, int ata)
Definition at line 582 of file csparse.c.
References cs_cedge(), cs_idone(), cs_malloc(), CS_MIN, cs_transpose(), cs_sparse::i, cs_sparse::m, cs_sparse::n, and cs_sparse::p.
Referenced by cs_schol(), and cs_sqr().
int cs_cumsum (int * p, int * c, int n)
Definition at line 651 of file csparse.c.
Referenced by cs_schol(), cs_symperm(), cs_transpose(), and cs_triplet().
int cs_dfs (int j, cs * L, int top, int * xi, int * pstack, const int * Pinv)
Definition at line 666 of file csparse.c.
References CS_MARK, CS_MARKED, CS_UNFLIP, cs_sparse::i, and cs_sparse::p.
Referenced by cs_reach(), and cs_scc().
int* cs_etree (const cs * A, int ata)
Definition at line 938 of file csparse.c.
References cs_idone(), cs_malloc(), cs_sparse::i, cs_sparse::m, cs_sparse::n, and cs_sparse::p.
Referenced by cs_schol(), and cs_sqr().
int cs_fkeep (cs * A, int(*)(int, int, double, void *) fkeep, void * other)
Definition at line 972 of file csparse.c.
References cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_amd(), cs_dmperm(), cs_droptol(), and cs_dropzeros().
double cs_house (double * x, double * beta, int n)
Definition at line 1040 of file csparse.c.
Referenced by cs_qr().
int* cs_maxtrans (const cs * A)
Definition at line 1359 of file csparse.c.
References cs_augment(), cs_calloc(), cs_idone(), cs_malloc(), cs_transpose(), cs_sparse::i, cs_sparse::m, cs_sparse::n, and cs_sparse::p.
Referenced by cs_dmperm().
int* cs_post (int n, const int * parent)
Definition at line 1499 of file csparse.c.
References cs_idone(), cs_malloc(), and cs_tdfs().
Referenced by cs_schol(), and cs_sqr().
int cs_reach (cs * L, const cs * B, int k, int * xi, const int * Pinv)
Definition at line 1728 of file csparse.c.
References cs_dfs(), CS_MARK, CS_MARKED, cs_sparse::i, cs_sparse::n, and cs_sparse::p.
Referenced by cs_splsolve().
csd* cs_scc (cs * A)
Definition at line 1774 of file csparse.c.
References cs_dalloc(), cs_ddone(), cs_dfs(), cs_malloc(), CS_MARK, CS_MARKED, cs_transpose(), cs_sparse::n, cs_dmperm_results::nb, cs_sparse::p, cs_dmperm_results::P, and cs_dmperm_results::R.
Referenced by cs_dmperm().
int cs_scatter (const cs * A, int j, double beta, int * w, double * x, int mark, cs * C, int nz)
Definition at line 1749 of file csparse.c.
References cs_sparse::i, cs_sparse::p, and cs_sparse::x.
Referenced by cs_add(), cs_multiply(), and cs_qr().
int cs_splsolve (cs * L, const cs * B, int k, int * xi, double * x, const int * Pinv)
Definition at line 1838 of file csparse.c.
References cs_reach(), cs_sparse::i, cs_sparse::n, cs_sparse::p, and cs_sparse::x.
Referenced by cs_lu().
int cs_tdfs (int j, int k, int * head, const int * next, int * post, int * stack)
Definition at line 1993 of file csparse.c.
Referenced by cs_amd(), and cs_post().
csd* cs_dalloc (int m, int n)
Definition at line 2201 of file csparse.c.
References cs_calloc(), cs_dfree(), cs_malloc(), cs_dmperm_results::P, cs_dmperm_results::Q, cs_dmperm_results::R, and cs_dmperm_results::S.
Referenced by cs_dmperm(), and cs_scc().
cs* cs_done (cs * C, void * w, void * x, int ok)
Definition at line 2225 of file csparse.c.
References cs_free(), and cs_spfree().
Referenced by cs_add(), cs_multiply(), cs_permute(), cs_symperm(), cs_transpose(), and cs_triplet().
int* cs_idone (int * p, cs * C, void * w, int ok)
Definition at line 2233 of file csparse.c.
References cs_free(), and cs_spfree().
Referenced by cs_amd(), cs_counts(), cs_etree(), cs_maxtrans(), cs_post(), and cs_vcount().
csn* cs_ndone (csn * N, cs * C, void * w, void * x, int ok)
Definition at line 2241 of file csparse.c.
References cs_free(), cs_nfree(), and cs_spfree().
Referenced by cs_chol(), cs_lu(), and cs_qr().
csd* cs_ddone (csd * D, cs * C, void * w, int ok)
Definition at line 2250 of file csparse.c.
References cs_dfree(), cs_free(), and cs_spfree().
Referenced by cs_dmperm(), and cs_scc().