fclib.h File Reference
#include `csparse.h`
*
Classes
struct fclib_info
This structure allows the user to enter a problem information as a title, a short description and known mathematical properties of the problem.
struct fclib_matrix_info
This structure allows the user to enter a description for a given matrix (comment, conditionning, determinant, rank.) if they are known.
struct fclib_matrix
matrix in compressed row/column or triplet form
struct fclib_global
The global frictional contact problem defined by.
struct fclib_local
The local frictional contact problem defined by.
struct fclib_solution
A solution or a guess for the frictional contact problem.
Enumerations
enum fclib_merit { MERIT_1,
MERIT_2
 }
MERIT_1 is a implementation of the merit function based on the natural map for a SOCCP.
Functions
int fclib_write_global (struct fclib_global *problem, const char *path)
write global problem; return 1 on success, 0 on failure
int fclib_write_local (struct fclib_local *problem, const char *path)
write local problem; return 1 on success, 0 on failure
int fclib_write_solution (struct fclib_solution *solution, const char *path)
write solution; return 1 on success, 0 on failure
int fclib_write_guesses (int number_of_guesses, struct fclib_solution *guesses, const char *path)
write initial guesses; return 1 on success, 0 on failure
struct fclib_global * fclib_read_global (const char *path)
read global problem; return problem on success; NULL on failure
struct fclib_local * fclib_read_local (const char *path)
read local problem; return problem on success; NULL on failure
struct fclib_solution * fclib_read_solution (const char *path)
read solution; return solution on success; NULL on failure
struct fclib_solution * fclib_read_guesses (const char *path, int *number_of_guesses)
read initial guesses; return vector of guesses on success; NULL on failure; output numebr of guesses in the variable pointed by 'number_of_guesses'
double fclib_merit_global (struct fclib_global *problem, enum fclib_merit merit, struct fclib_solution *solution)
calculate merit function for a global problem
double fclib_merit_local (struct fclib_local *problem, enum fclib_merit merit, struct fclib_solution *solution)
calculate merit function for a local problem
void fclib_delete_global (struct fclib_global *problem)
delete global problem
void fclib_delete_local (struct fclib_local *problem)
delete local problem
void fclib_delete_solutions (struct fclib_solution *data, int count)
delete solutions or guesses
Detailed Description
frictional contact library interface
This C API provides functions to read and write Frictional contact problemes in HDF5 format Two kind of problem are considered Given
a symmetric positive semi--definite matrix ${W} \in {\mathrm{I\!R}}^{m \times m} $
a vector $ {q} \in {\mathrm{I\!R}}^m$
a vector of coefficients of friction $\mu \in{\mathrm{I\!R}}^{n_c}$
the local FC problem is to find two vectors $u\in{\ensuremath{\mathrm{I\!R}}}^m$, the relative local velocity and $r\in {\ensuremath{\mathrm{I\!R}}}^m$, the contact forces denoted by $\mathrm{FC}(W,q,\mu)$ such that
 \begin{cases} \hat u = W r + q +\left[ \left[\begin{array}{c} \mu^\alpha \|u^\alpha_T\|\ \ 0 \ \ 0 \end{array}\right]^T, \alpha = 1 \ldots n_c \right]^T \\ \ \ C^\star_{\mu} \ni {\hat u} \perp r \in C_{\mu} \end{cases} 
 where the Coulomb friction cone for a contact $\alpha$ is defined by
 \label{eq:CCC} C_{\mu^\alpha}^{\alpha} = \{r^\alpha, \|r^\alpha_T \| \leq \mu^\alpha |r^\alpha_N| \} *
 and the set $C^{\alpha,\star}_{\mu^\alpha}$ is its dual. We are also dealing with global FC problem defined by Given
a symmetric positive definite matrix ${M} \in {\mathrm{I\!R}}^{n \times n}$
a vector $ {f} \in {\mathrm{I\!R}}^n$,
a matrix ${H} \in {\mathrm{I\!R}}^{n \times m}$
a matrix ${G} \in {\mathrm{I\!R}}^{n \times p}$
a vector $w \in {\mathrm{I\!R}}^{m}$,
a vector $b \in {\mathrm{I\!R}}^{p}$,
a vector of coefficients of friction $\mu \in {\mathrm{I\!R}}^{n_c}$
the Global Mixed 3DFC problem is to find four vectors $ {v} \in {\mathrm{I\!R}}^n$, $u\in{\mathrm{I\!R}}^m$, $r\in {\mathrm{I\!R}}^m$ and $\lambda \in {\mathrm{I\!R}}^p$ denoted by $\mathrm{GM3DFC}(M,H,G,w,b,\mu)$ such that
 \begin{cases} M v = {H} {r} + G\lambda + {f} \\ \ \ G^T v +b =0 \\ \ \ \hat u = H^T v + w +\left[ \left[\begin{array}{c} \mu \|u^\alpha_T\|\ \ 0 \ \ 0 \end{array}\right]^T, \alpha = 1 \ldots n_c \right]^T \\ \ \ C^\star_{\mu} \ni {\hat u} \perp r \in C_{\mu} \end{cases} 
Definition in file fclib.h.
Enumeration Type Documentation
enum fclib_merit
MERIT_1 is a implementation of the merit function based on the natural map for a SOCCP.
Enumerator
MERIT_1
MERIT_2
Definition at line 269 of file fclib.h.
Function Documentation
int fclib_write_global (struct fclib_global * problem, const char * path)
write global problem; return 1 on success, 0 on failure
Definition at line 386 of file fclib.c.
References ASSERT, fclib_global::G, fclib_global::H, H5Gmake(), fclib_global::info, IO, fclib_global::M, fclib_global::spacedim, write_global_vectors(), write_matrix(), and write_problem_info().
Referenced by main().
int fclib_write_local (struct fclib_local * problem, const char * path)
write local problem; return 1 on success, 0 on failure
Definition at line 454 of file fclib.c.
References ASSERT, H5Gmake(), fclib_local::info, IO, fclib_local::R, fclib_local::spacedim, fclib_local::V, fclib_local::W, write_local_vectors(), write_matrix(), and write_problem_info().
Referenced by main().
int fclib_write_solution (struct fclib_solution * solution, const char * path)
write solution; return 1 on success, 0 on failure
Definition at line 522 of file fclib.c.
References H5Gmake(), IO, read_nvnunrnl(), and write_solution().
Referenced by main().
int fclib_write_guesses (int number_of_guesses, struct fclib_solution * guesses, const char * path)
write initial guesses; return 1 on success, 0 on failure
Definition at line 562 of file fclib.c.
References H5Gmake(), IO, read_nvnunrnl(), and write_solution().
Referenced by main().
struct fclib_global* fclib_read_global (const char * path)
read global problem; return problem on success; NULL on failure
Definition at line 612 of file fclib.c.
References fclib_global::G, fclib_global::H, fclib_global::info, IO, fclib_global::M, MM, read_global_vectors(), read_matrix(), read_problem_info(), and fclib_global::spacedim.
Referenced by main().
struct fclib_local* fclib_read_local (const char * path)
read local problem; return problem on success; NULL on failure
Definition at line 662 of file fclib.c.
References fclib_local::info, IO, MM, fclib_local::R, read_local_vectors(), read_matrix(), read_problem_info(), fclib_local::spacedim, fclib_local::V, and fclib_local::W.
Referenced by main().
struct fclib_solution* fclib_read_solution (const char * path)
read solution; return solution on success; NULL on failure
Definition at line 712 of file fclib.c.
References IO, MM, read_nvnunrnl(), and read_solution().
Referenced by main().
struct fclib_solution* fclib_read_guesses (const char * path, int * number_of_guesses)
read initial guesses; return vector of guesses on success; NULL on failure; output numebr of guesses in the variable pointed by 'number_of_guesses'
Definition at line 740 of file fclib.c.
References IO, MM, read_nvnunrnl(), and read_solution().
Referenced by main().
double fclib_merit_global (struct fclib_global * problem, enum fclib_merit merit, struct fclib_solution * solution)
calculate merit function for a global problem
Definition at line 80 of file fcmer.c.
Referenced by main().
double fclib_merit_local (struct fclib_local * problem, enum fclib_merit merit, struct fclib_solution * solution)
calculate merit function for a local problem
Definition at line 86 of file fcmer.c.
References cs_gaxpy(), cs_transpose(), dnrm2(), FrictionContact3D_unitary_compute_and_add_error(), fclib_matrix::i, fclib_solution::l, MERIT_1, fclib_local::mu, fclib_matrix::n, fclib_local::q, fclib_local::R, fclib_solution::r, fclib_local::s, fclib_local::spacedim, fclib_solution::u, fclib_local::V, fclib_solution::v, and fclib_local::W.
Referenced by main().
void fclib_delete_global (struct fclib_global * problem)
delete global problem
Definition at line 780 of file fclib.c.
References fclib_global::b, delete_info(), delete_matrix(), fclib_global::f, fclib_global::G, fclib_global::H, fclib_global::info, fclib_global::M, fclib_global::mu, and fclib_global::w.
Referenced by main().
void fclib_delete_local (struct fclib_local * problem)
delete local problem
Definition at line 793 of file fclib.c.
References delete_info(), delete_matrix(), fclib_local::info, fclib_local::mu, fclib_local::q, fclib_local::R, fclib_local::s, fclib_local::V, and fclib_local::W.
Referenced by main().
void fclib_delete_solutions (struct fclib_solution * data, int count)
delete solutions or guesses
Definition at line 805 of file fclib.c.
References fclib_solution::l, fclib_solution::r, fclib_solution::u, and fclib_solution::v.
Referenced by main().