#
# Siconos documentation with Doxygen 
#

# # Style sheet
# FILE(GLOB CSS_FILES config/css/*.* config/css/*)
# FOREACH(FILE ${CSS_FILES})
#  IF(NOT IS_DIRECTORY ${FILE})
#    MESSAGE(STATUS "Copy " ${FILE} " to " ${CMAKE_BINARY_DIR}/${RFILE})
#    FILE(RELATIVE_PATH RFILE ${CMAKE_SOURCE_DIR} ${FILE})
#    CONFIGURE_FILE(${FILE} ${CMAKE_BINARY_DIR}/${RFILE} COPYONLY)
#  ENDIF(NOT IS_DIRECTORY ${FILE})
# ENDFOREACH(FILE ${CSS_FILES})






# build in Generated DOCS
IF (NOT DOXYGEN_OUTPUT)
  SET(DOXYGEN_OUTPUT ${CMAKE_SOURCE_DIR}/../web)
ENDIF(NOT DOXYGEN_OUTPUT)

# Style sheet
FILE(GLOB CSS_FILES config/css/*.*)
FOREACH(FILE ${CSS_FILES})
 IF(NOT IS_DIRECTORY ${FILE})
   FILE(RELATIVE_PATH RFILE ${CMAKE_SOURCE_DIR}/config/css ${FILE})
   MESSAGE(STATUS "Copy " ${FILE} " to " ${DOXYGEN_OUTPUT}/${RFILE})
   CONFIGURE_FILE(${FILE} ${DOXYGEN_OUTPUT}/${RFILE} COPYONLY)
 ENDIF(NOT IS_DIRECTORY ${FILE})
ENDFOREACH(FILE ${CSS_FILES})

# Images file
FILE(GLOB IMG_FILES config/images/*.*)
FOREACH(FILE ${IMG_FILES})
 IF(NOT IS_DIRECTORY ${FILE})
   FILE(RELATIVE_PATH RFILE ${CMAKE_SOURCE_DIR}/config/  ${FILE})
   MESSAGE(STATUS "Copy " ${FILE} " to " ${DOXYGEN_OUTPUT}/${RFILE})
   CONFIGURE_FILE(${FILE} ${DOXYGEN_OUTPUT}/${RFILE} COPYONLY)
 ENDIF(NOT IS_DIRECTORY ${FILE})
ENDFOREACH(FILE ${IMG_FILES})

# LATEX Style
FILE(GLOB LATEX_FILES config/*.sty)
FOREACH(FILE ${LATEX_FILES})
 IF(NOT IS_DIRECTORY ${FILE})
   FILE(RELATIVE_PATH RFILE ${CMAKE_SOURCE_DIR}/config/  ${FILE})
   MESSAGE(STATUS "Copy " ${FILE} " to " ${DOXYGEN_OUTPUT}/${RFILE})
   CONFIGURE_FILE(${FILE} ${DOXYGEN_OUTPUT}/${RFILE} COPYONLY)
 ENDIF(NOT IS_DIRECTORY ${FILE})
ENDFOREACH(FILE ${LATEX_FILES})

# PDF files
FILE(GLOB PDF ../doc/FCLib.pdf)
FOREACH(FILE ${PDF})
 IF(NOT IS_DIRECTORY ${FILE})
   FILE(RELATIVE_PATH RFILE ${CMAKE_SOURCE_DIR}/../  ${FILE})
   MESSAGE(STATUS "Copy " ${FILE} " to " ${DOXYGEN_OUTPUT}/${RFILE})
   CONFIGURE_FILE(${FILE} ${DOXYGEN_OUTPUT}/${RFILE} COPYONLY)
 ENDIF(NOT IS_DIRECTORY ${FILE})
ENDFOREACH(FILE ${PDF_FILES})



FILE(MAKE_DIRECTORY ${DOXYGEN_OUTPUT})
FILE(MAKE_DIRECTORY ${DOXYGEN_OUTPUT}/${PROJECT})
FILE(MAKE_DIRECTORY ${DOXYGEN_OUTPUT}/Tags)
FILE(MAKE_DIRECTORY ${DOXYGEN_OUTPUT}/images)
FILE(MAKE_DIRECTORY ${DOXYGEN_OUTPUT}/doc)


INCLUDE(TargetDoc OPTIONAL)
